### ISSUE TITLE
Is it safe to push identity to Git?

### ISSUE THREAD

**Issue by samchouse** [bromanko/age-plugin-op#2]
Basically the title. I've taken a look at the source code but I'm not sure how age plugins work so it's a bit hard for me to tell.

**Comment by bromanko** [comment]
The [identity struct](https://github.com/bromanko/age-plugin-op/blob/f4dc4bea66e54526a12a1bec5217131b11fe9ebc/plugin/identity.go) contains two pieces of information: 
- The path in 1Password to the private key (the one passed as an argument to `--generate`)
- A version identifier

It's your call whether these details are sensitive or not.

**Comment by bromanko** [comment]
As far as whether publishing the identity file enables someone to decrypt your secrets, in general, no. You would also need access to the 1Password vault to decrypt. The private key is only contained within 1Password.

**Comment by samchouse** [comment]
Perfect, thank you!
